Hobbies1/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hobbies1.Controllers
{
    public class DataController : Controller
    {
        // GET: Data
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hobbies1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hobbies1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hobbies1/Views/Data/Index.cshtml
@{
    List<string> liste = new List<string>();
    liste.Add("Veuf");
    liste.Add("Marié(e)");
    liste.Add("Célibataire");
    liste.Add("Compliqué");

}


@using (Html.BeginForm("Index", "Data", FormMethod.Post, new { style = "margin-left:10px;" }))
{
    @MesHelpers.ShowMessage("Salut!")
    
    <container id="test" style="margin-left:10px;">
        <div class="row justify-content-center">

            <div class="col col-1">
                @Html.Label("m", "Homme")
                @Html.CheckBox("m", false)
            </div>
            <div class="col col-1">

                @Html.Label("f", "Femme")
                @Html.CheckBox("f", false)

            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("firstName", "Prénom")

            </div>
            <div class="col col-1">
                @Html.TextBox("firstName", "")

            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("lastName", "Nom")
            </div>
            <div class="col col-1">
                @Html.TextBox("lastName", "")
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("liste", "Statut marital")
            </div>
            <div class="col col-1">
                @Html.DropDownList("liste", new SelectList(liste))
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("userName", "Login")
            </div>
            <div class="col col-1">
                @Html.TextBox("userName", "")
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("password", "Mot de passe")
            </div>
            <div class="col col-1">
                @Html.Password("password", "")
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                @Html.Label("date", "Date de naissance")
            </div>
            <div class="col col-1">
               <input id="date" type="date" style="width:168px;" />
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col col-1">
                <button type="submit">Valider</button>
            </div>
        </div>
       
    </container>
}

Hobbies1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row">
        <div class="col col-12 text-center">
            <h2 class="text-center">Album example</h2>
            <p class="text-align-center">Something short and leading about the collection below - its contents,ther creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely</p>
            <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Main call to action</a>
            <a href="#" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Secondary Action</a>
            <br />
            <br />
            <br />

        </div>
    </div>
    <div class="row">
        <div class="col col-4">
            <div class="card">
                <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" style="height: 180px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_167c6bec48a%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_167c6bec48a%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.203125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <button type="button" class="btn btn-outline-secondary">View</button><button type="button" class="btn btn-outline-secondary">Edit</button>
                </div>
            </div>
        </div>
        <div class="col col-4">
            <div class="card">
                <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" style="height: 180px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_167c6bec48a%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_167c6bec48a%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.203125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <button type="button" class="btn btn-outline-secondary">View</button><button type="button" class="btn btn-outline-secondary">Edit</button>
                </div>
            </div>
        </div>
        <div class="col col-4">
            <div class="card">
                <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" style="height: 180px; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22286%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20286%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_167c6bec48a%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_167c6bec48a%22%3E%3Crect%20width%3D%22286%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22107.203125%22%20y%3D%2296.3%22%3E286x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <button type="button" class="btn btn-outline-secondary">View</button><button type="button" class="btn btn-outline-secondary">Edit</button>
                </div>
            </div>
        </div>
    </div>
</div>

Hobbies1/Views/Shared/_Layout.cshtml
@{

    if (ViewBag.Title == null)
    {
        ViewBag.Title = "Album";
    }
}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <link rel="stylesheet" href="~/Content/Site.css" />
    
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/JavaScript.js"></script>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand fa fa-camera" href="/home/index">Album</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="/data/index">Formulaire<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <div style="margin-top: 60px; padding-bottom:60px;">

        @RenderBody()
        <div class="container-fluid" style="width:100%;">
            <footer>
                <hr />
                <div id="myTextCentered" style="background-color:white;">
                    &copy; @DateTime.Now.Year - C'est de la merde
                </div>
            </footer>
        </div>
    </div>
</body>
</html>